class Board:
    colors = ['blue', 'brown', 'green', 'yellow', 'orange', 'pink']

    squares = {
        '0': 'start',
        'a1': 'orange',
        'a2': 'pink',
        'a3': 'green',
        'a4': 'blue',
        'a5': 'brown',
        'a6': 'yellow',
        'a7': 'brown',
        'a8': 'roll again',
        'a9': 'green',
        'a10': 'orange',
        'a11': 'roll again',
        'a12': 'blue',
        'b1': 'yellow',
        'b2': 'green',
        'b3': 'brown',
        'b4': 'orange',
        'b5': 'blue',
        'b6': 'pink',
        'b7': 'blue',
        'b8': 'roll again',
        'b9': 'brown',
        'b10': 'yellow',
        'b11': 'roll again',
        'b12': 'orange',
        'c1': 'pink',
        'c2': 'brown',
        'c3': 'blue',
        'c4': 'yellow',
        'c5': 'orange',
        'c6': 'green',
        'c7': 'orange',
        'c8': 'roll again',
        'c9': 'blue',
        'c10': 'pink',
        'c11': 'roll again',
        'c12': 'yellow',
        'd1': 'green',
        'd2': 'blue',
        'd3': 'orange',
        'd4': 'pink',
        'd5': 'yellow',
        'd6': 'brown',
        'd7': 'yellow',
        'd8': 'roll again',
        'd9': 'orange',
        'd10': 'green',
        'd11': 'roll again',
        'd12': 'pink',
        'e1': 'brown',
        'e2': 'orange',
        'e3': 'yellow',
        'e4': 'green',
        'e5': 'pink',
        'e6': 'blue',
        'e7': 'pink',
        'e8': 'roll again',
        'e9': 'yellow',
        'e10': 'brown',
        'e11': 'roll again',
        'e12': 'green',
        'f1': 'blue',
        'f2': 'yellow',
        'f3': 'pink',
        'f4': 'brown',
        'f5': 'green',
        'f6': 'orange',
        'f7': 'green',
        'f8': 'roll again',
        'f9': 'pink',
        'f10': 'blue',
        'f11': 'roll again',
        'f12': 'brown'
    }
    
    start = '0'
    special_squares = ['a6', 'b6', 'c6', 'd6', 'e6', 'f6']

